# Default initial positions for ur10e's ros2_control fake system

initial_positions:
  # elbow_joint: 0
  finger_joint: 0
  # shoulder_lift_joint: 0
  # shoulder_pan_joint: 0
  shoulder_pan_joint: 2.4464e+00
  shoulder_lift_joint: -9.7604e-01
  elbow_joint: 1.783522907887594
  wrist_1_joint: -2.3782e+00
  wrist_2_joint: -1.5708e+00
  wrist_3_joint: 5.8318e-01